# Generated by Django 5.1.4 on 2025-01-09 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.CharField(max_length=200)),
                ('Cantidad', models.CharField(max_length=200)),
                ('Serial', models.CharField(max_length=200)),
                ('Bien_Nacional', models.CharField(max_length=200)),
                ('Nota', models.TextField(blank=True)),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
